# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

# Fabric Properties
   minecraft_version=26.1
   loader_version=0.18.4

fabric_version=0.144.1+26.1
modmenu_version=18.0.0-alpha.7

# Mod Properties
   maven_group = com.unascribed
   archives_base_name = ears-fabric-26.1
