buildscript {
	repositories {
		mavenCentral()
		maven { url "https://maven.fabricmc.net" }
		maven { url "https://repo.sleeping.town" }
	}
	dependencies {
		classpath "agency.highlysuspect:voldeloom:2.5-SNAPSHOT"
	}
}

apply plugin: "agency.highlysuspect.voldeloom"

version = file('../version.txt').text.trim()+file('version-suffix.txt').text.trim()
group= "com.unascribed.ears" // http://maven.apache.org/guides/mini/guide-naming-conventions.html
archivesBaseName = "ears-forge-1.7"

sourceCompatibility = targetCompatibility = 8

jar {
	manifest {
		attributes (
			'FMLCorePlugin': 'com.unascribed.ears.common.agent.OldForgeCoremod',
			'FMLCorePluginContainsFMLMod': true
		)
	}
}

configurations {
	retrolambda
}

task retrolambda(type: JavaExec) {
	dependsOn compileJava
	
	javaLauncher = javaToolchains.launcherFor {
		languageVersion = JavaLanguageVersion.of(8)
	}
	
	doFirst {
		def rl = configurations.retrolambda.resolve().iterator().next()
		
		classpath = files(rl)
		
		def out = compileJava.destinationDirectory.getAsFile().get().getAbsolutePath()
		
		jvmArgs(
			'-Dretrolambda.inputDir='+out,
			'-Dretrolambda.classpath='+compileJava.classpath.getAsPath()+File.pathSeparator+out,
			'-Dretrolambda.bytecodeVersion=50',
			'-Dretrolambda.quiet=true'
		)
	}
}

compileJava.finalizedBy retrolambda

dependencies {
	implementation files('../common/build/libs/ears-common-agent-vlegacy.jar')
	
	retrolambda 'net.orfjackal.retrolambda:retrolambda:2.5.7'
	minecraft "com.mojang:minecraft:1.7.10"
	forge "net.minecraftforge:forge:1.7.10-10.13.4.1614-1.7.10:universal"
	mappings volde.layered {
		importMCPBot("https://mcpbot.unascribed.com/", "1.7.10", "stable", "12-1.7.10")
	}
}

jar {
	from zipTree('../common/build/libs/ears-common-agent-vlegacy.jar')
}

processResources {
	inputs.property "version", project.version
	
	filesMatching("mcmod.info") {
		expand 'version': project.version, 'mcversion': '1.7.10'
	}
}

compileJava.doFirst {
	'../common/replace-version.sh src/main/java/com/unascribed/ears/Ears.java src/main/java/com/unascribed/ears/EarsPlatformVersion.java'.execute()
}
